services:
  - type: web
    name: travel-app-backend
    env: node
    buildCommand: npm install && cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: travel-app-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://hopeday.netlify.app
